#!/usr/bin/env node
// Packs the browser GUI (public/index.html), the crowd faces (public/people/*.webp) and the
// package version into src/generated/assets.ts, so the game never has to read them from disk.
// That lets a single compiled executable carry everything it needs.
//
// Runs automatically before build, dev, test and typecheck (see package.json "pre" scripts).
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const page = readFileSync(join(root, 'public/index.html'), 'utf8');

const peopleDir = join(root, 'public/people');
const people = {};
for (const name of readdirSync(peopleDir).sort()) {
  if (/^[a-z0-9-]+\.webp$/.test(name)) people[name] = readFileSync(join(peopleDir, name)).toString('base64');
}

const out = `// Generated by scripts/embed-assets.mjs from public/ and package.json. Do not edit.
export const VERSION = ${JSON.stringify(version)};
export const PAGE_HTML = ${JSON.stringify(page)};
/** Crowd face images, base64-encoded WebP, by file name. */
export const PEOPLE_WEBP: Record<string, string> = ${JSON.stringify(people, null, 1)};
`;

mkdirSync(join(root, 'src/generated'), { recursive: true });
writeFileSync(join(root, 'src/generated/assets.ts'), out);
console.log(`embedded GUI + ${Object.keys(people).length} faces (v${version}) into src/generated/assets.ts`);
